### PR TITLE
bug: add rechecking of event after closing a campaign to handle same campaign triggered multiple times

### PR DESCRIPTION
**Pull request by vincentdelmundo**
# Description
**Before:**
* When the same campaign is triggered multiple times (event is triggered multiple times before or while the campaign is displayed), the next display of the same campaign will not be done on close of the current campaign. It will be displayed on session update or next event trigger (even if the a different event is triggered)

**After:**
* On close of a campaign, checking of triggered events will be re-executed to check if another campaign should be displayed.

**Others:**
* added buttons for triggering multiple events (same and different events) on one click

## Links
https://jira.rakuten-it.com/jira/browse/SDKCF-2872

# Checklist
- [x] I have read the [contributing guidelines](../CONTRIBUTING.md).
- [x] I wrote/updated tests for new/changed code
- [x] I ran `./gradlew check` without errors

### CODE REVIEW

**Review by imaginaris — APPROVED** [review]
Looks good to me 👍

**Review by imaginaris — COMMENTED** [review]
There is still a question what should we do if a campaign was cancelled by the host app using new `onVerifyContext()` callback. Do we also need some handling there (DisplayMessageJobIntentService class)

**Comment by vincentdelmundo** [comment]
> There is still a question what should we do if a campaign was cancelled by the host app using new `onVerifyContext()` callback. Do we also need some handling there (DisplayMessageJobIntentService class)

@imaginaris 
Maybe instead of depending on `ReadyForDisplayMessageRepository` in the `prepareNextMessage` , we can create a copy of the messages from the repository so `DisplayMessageJobIntentService` class will handle the traversing of the list

**Review by MdUsmanGani — APPROVED** [review]
LGTM

**Review by corycaywood — APPROVED** [review]
👍

**Pull request merged**
