### PR TITLE
feat: update minimum SDK to API 23

### PR DESCRIPTION
**Pull request by leila-gu**
# Checklist
- [x] I have read the [contributing guidelines](../CONTRIBUTING.md).
- [x] I wrote/updated tests for new/changed code
- [ ] I removed all sensitive data **before every commit**, including API endpoints and keys
- [x] I checked that all possible internal and platform/library exceptions are gracefully handled and **will not** crash the host app
- [ ] I checked for open & known issues (especially crashes) for any newly added platform APIs or libraries
- [x] I tested non-trivial changes on a real device
- [x] I ran `./gradlew check` without errors

### CODE REVIEW

**Review by vincentdelmundo — APPROVED** [review]
LGTM

**Review by imaginaris — CHANGES_REQUESTED** [review]
@leila-gu Please update also USERGUIDE.md (line 22 and 58)

**Comment by leila-gu** [comment]
> @leila-gu Please update also USERGUIDE.md (line 22 and 58)

@imaginaris thank you for noticing that! 
updated!

**Review by vincentdelmundo — APPROVED** [review]
LGTM

**Review by imaginaris — APPROVED** [review]

**Pull request merged**
