### PR TITLE
improve: validate triggers for test campaigns (SDKCF-5777)

### PR DESCRIPTION
**Pull request by maureenorea-clores**
# Checklist
- [x] I have read the [contributing guidelines](../CONTRIBUTING.md).
- [x] I wrote/updated tests for new/changed code
- [x] I removed all sensitive data **before every commit**, including API endpoints and keys
- [ ] I checked that all possible internal and platform/library exceptions are gracefully handled and **will not** crash the host app
- [ ] I checked for open & known issues (especially crashes) for any newly added platform APIs or libraries
- [ ] I tested non-trivial changes on a real device
- [x] I added ticket/changes in changelog
- [x] I ran `./gradlew check` without errors

### CODE REVIEW

**Review by vincentdelmundo — APPROVED** [review]
LGTM

**Review by mdusmangani-jp — APPROVED** [review]
LGTM

**Review by imaginaris — APPROVED** [review]
LGTM

**Comment by maureenorea-clores** [comment]
This needs to wait until tested with backend

**Pull request merged**
